logging.level.ru.cbr.demorestservice.rest: debug
server:
  port: 8081
  servlet.context-path: /api
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  main.allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo-rest
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
