server:
  port: 8081
spring:
  main.allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:demo-rest
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.H2Dialect
  data:
    rest:
      base-path: /api
logging.level.ru.cbr.demorestservice.rest: debug
